<?php

namespace ContainerALPcyF4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__5ICgTMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..5ICgTM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..5ICgTM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'vieNote' => ['privates', '.errored..service_locator..5ICgTM.App\\Entity\\VieNote', NULL, 'Cannot autowire service ".service_locator..5ICgTM": it needs an instance of "App\\Entity\\VieNote" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'vieNote' => 'App\\Entity\\VieNote',
            'entityManager' => '?',
        ]);
    }
}
