<?php

namespace ContainerALPcyF4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEtatControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tpz9p2x.App\Controller\EtatController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tpz9p2x.App\\Controller\\EtatController::delete()'] = ($container->privates['.service_locator.tpz9p2x'] ?? $container->load('get_ServiceLocator_Tpz9p2xService'))->withContext('App\\Controller\\EtatController::delete()', $container);
    }
}
