<?php

namespace ContainerALPcyF4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEtat2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.tpz9p2x.App\Entity\Etat' shared service.
     *
     * @return \App\Entity\Etat
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.tpz9p2x": it needs an instance of "App\\Entity\\Etat" but this type has been excluded in "config/services.yaml".');
    }
}
