<?php

namespace ContainerALPcyF4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEtatControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tsi9WYZ.App\Controller\EtatController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tsi9WYZ.App\\Controller\\EtatController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'etatRepository' => ['privates', 'App\\Repository\\EtatRepository', 'getEtatRepositoryService', true],
        ], [
            'etatRepository' => 'App\\Repository\\EtatRepository',
        ]))->withContext('App\\Controller\\EtatController::index()', $container);
    }
}
