<?php

namespace ContainerALPcyF4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNote2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ezrk3EG.App\Entity\Note' shared service.
     *
     * @return \App\Entity\Note
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ezrk3EG": it needs an instance of "App\\Entity\\Note" but this type has been excluded in "config/services.yaml".');
    }
}
