<?php

namespace ContainerALPcyF4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNoteControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ezrk3EG.App\Controller\NoteController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ezrk3EG.App\\Controller\\NoteController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'note' => ['privates', '.errored..service_locator.ezrk3EG.App\\Entity\\Note', NULL, 'Cannot autowire service ".service_locator.ezrk3EG": it needs an instance of "App\\Entity\\Note" but this type has been excluded in "config/services.yaml".'],
        ], [
            'note' => 'App\\Entity\\Note',
        ]))->withContext('App\\Controller\\NoteController::show()', $container);
    }
}
