<?php

namespace ContainerALPcyF4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNoteControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OEyoXXN.App\Controller\NoteController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.OEyoXXN'] ?? $container->load('get_ServiceLocator_OEyoXXNService'));

        if (isset($container->privates['.service_locator.OEyoXXN.App\\Controller\\NoteController::edit()'])) {
            return $container->privates['.service_locator.OEyoXXN.App\\Controller\\NoteController::edit()'];
        }

        return $container->privates['.service_locator.OEyoXXN.App\\Controller\\NoteController::edit()'] = $a->withContext('App\\Controller\\NoteController::edit()', $container);
    }
}
