<?php

namespace ContainerALPcyF4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTagControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SXP7cLa.App\Controller\TagController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SXP7cLa.App\\Controller\\TagController::delete()'] = ($container->privates['.service_locator.SXP7cLa'] ?? $container->load('get_ServiceLocator_SXP7cLaService'))->withContext('App\\Controller\\TagController::delete()', $container);
    }
}
