<?php

namespace ContainerALPcyF4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVieNoteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..5ICgTM.App\Entity\VieNote' shared service.
     *
     * @return \App\Entity\VieNote
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator..5ICgTM": it needs an instance of "App\\Entity\\VieNote" but this type has been excluded in "config/services.yaml".');
    }
}
