<?php

namespace ContainerOytwzqQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEtatControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AsiqGOS.App\Controller\EtatController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AsiqGOS.App\\Controller\\EtatController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'etat' => ['privates', '.errored..service_locator.AsiqGOS.App\\Entity\\Etat', NULL, 'Cannot autowire service ".service_locator.AsiqGOS": it needs an instance of "App\\Entity\\Etat" but this type has been excluded in "config/services.yaml".'],
        ], [
            'etat' => 'App\\Entity\\Etat',
        ]))->withContext('App\\Controller\\EtatController::show()', $container);
    }
}
