<?php

namespace ContainerOytwzqQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEtatControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tpz9p2x.App\Controller\EtatController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.tpz9p2x'] ?? $container->load('get_ServiceLocator_Tpz9p2xService'));

        if (isset($container->privates['.service_locator.tpz9p2x.App\\Controller\\EtatController::edit()'])) {
            return $container->privates['.service_locator.tpz9p2x.App\\Controller\\EtatController::edit()'];
        }

        return $container->privates['.service_locator.tpz9p2x.App\\Controller\\EtatController::edit()'] = $a->withContext('App\\Controller\\EtatController::edit()', $container);
    }
}
