<?php

namespace ContainerOytwzqQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNoteControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Q8faQP1.App\Controller\NoteController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Q8faQP1.App\\Controller\\NoteController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'noteRepository' => ['privates', 'App\\Repository\\NoteRepository', 'getNoteRepositoryService', true],
        ], [
            'noteRepository' => 'App\\Repository\\NoteRepository',
        ]))->withContext('App\\Controller\\NoteController::index()', $container);
    }
}
