<?php

namespace ContainerOytwzqQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTagControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SXP7cLa.App\Controller\TagController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.SXP7cLa'] ?? $container->load('get_ServiceLocator_SXP7cLaService'));

        if (isset($container->privates['.service_locator.SXP7cLa.App\\Controller\\TagController::edit()'])) {
            return $container->privates['.service_locator.SXP7cLa.App\\Controller\\TagController::edit()'];
        }

        return $container->privates['.service_locator.SXP7cLa.App\\Controller\\TagController::edit()'] = $a->withContext('App\\Controller\\TagController::edit()', $container);
    }
}
