<?php

namespace ContainerOytwzqQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTagControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.78wiA30.App\Controller\TagController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.78wiA30.App\\Controller\\TagController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tag' => ['privates', '.errored..service_locator.78wiA30.App\\Entity\\Tag', NULL, 'Cannot autowire service ".service_locator.78wiA30": it needs an instance of "App\\Entity\\Tag" but this type has been excluded in "config/services.yaml".'],
        ], [
            'tag' => 'App\\Entity\\Tag',
        ]))->withContext('App\\Controller\\TagController::show()', $container);
    }
}
