<?php

namespace ContainerOytwzqQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVieNoteControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..5ICgTM.App\Controller\VieNoteController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..5ICgTM.App\\Controller\\VieNoteController::delete()'] = ($container->privates['.service_locator..5ICgTM'] ?? $container->load('get_ServiceLocator__5ICgTMService'))->withContext('App\\Controller\\VieNoteController::delete()', $container);
    }
}
