<?php

namespace ContainerOytwzqQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVieNoteControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oE7LkR_.App\Controller\VieNoteController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oE7LkR_.App\\Controller\\VieNoteController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'vieNote' => ['privates', '.errored..service_locator.oE7LkR_.App\\Entity\\VieNote', NULL, 'Cannot autowire service ".service_locator.oE7LkR_": it needs an instance of "App\\Entity\\VieNote" but this type has been excluded in "config/services.yaml".'],
        ], [
            'vieNote' => 'App\\Entity\\VieNote',
        ]))->withContext('App\\Controller\\VieNoteController::show()', $container);
    }
}
