<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerALPcyF4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerALPcyF4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerALPcyF4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerALPcyF4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerALPcyF4\App_KernelDevDebugContainer([
    'container.build_hash' => 'ALPcyF4',
    'container.build_id' => '2960ae1a',
    'container.build_time' => 1747986644,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerALPcyF4');
